// Generated by `pnpm hud:keys` from the pictures in hud/banners/ and hud/art/.
// Never edited by hand: a key is a file in the addon, and hud/test/keys.test.ts
// fails when this list and those folders disagree.

/** Every banner the addon ships, by key (`hud/banners/<key>.png`). */
export const HUD_BANNER_KEYS = ['default'] as const

/** Every moment picture the addon ships, by key (`hud/art/<key>.png`). */
export const HUD_ART_KEYS = [
  'big-bag',
  'big-crewneck',
  'big-flag',
  'big-gobig-tee',
  'big-home-jersey',
  'big-jersey',
  'big-keyring',
  'big-lanyard',
  'big-lollipop',
  'big-mousepad',
  'big-origins-tee',
  'big-pin',
  'big-roar-tee',
  'big-sticker',
  'category-catering',
  'category-gift-card',
  'category-merch',
  'category-prize',
  'double-sandwich',
  'double-waffel',
  'empty',
  'karlsberg',
  'kuscheln-am-infopoint',
  'saarlan-becher',
  'saarlan-cup',
  'shot',
] as const
