/**
 * **The moment's pictures** (PRD-07 T7). A picture is a file with a key,
 * `hud/art/<key>.png`, and nothing can put a picture on a HUD at runtime: the
 * plugin sets a class on the card (`art-<key>`) and a stylesheet says which
 * picture that class means. So the stylesheet is written from the folder, the
 * way the welcome's banners are (`banners.ts`), and a test fails when the two
 * disagree. No class, or a class for a key the addon does not hold, is the
 * platform's empty card sleeve, `empty`: the rule for the picture's own box
 * names it, and only a class this file knows overrides it.
 *
 * The pictures are the platform's house drop art at 1× (at most 384 px a
 * side), as they are. The card's picture box is smaller than that on a 1080p
 * screen and about that size on a 4K one, so nothing is fitted or resized
 * here.
 */

/** Where the generated stylesheet lives, relative to `hud/`. */
export const ART_STYLES = 'styles/ezpug_art.css'

/** A picture as the stylesheet names it: the compiled texture in the addon. */
export const artTexture = (key: string) => `s2r://panorama/images/custom_game/ezpug/art/${key}.vtex`

/** The stylesheet the moment includes for its card's picture, as source. */
export function renderArtStyles(keys: string[], fallback: string): string {
  const rule = (selector: string, key: string) =>
    `${selector}\n{\n\tbackground-image: url( "${artTexture(key)}" );\n}\n`
  return [
    `/*
  Generated by \`pnpm hud:keys\` from the pictures in hud/art/.
  Never edited by hand: hud/test/art.test.ts fails when this file and that folder
  disagree. The empty sleeve unless the card carries a class for a key this addon holds.
*/
`,
    rule('.ezpug-moment-art', fallback),
    ...keys
      .filter(key => key !== fallback)
      .map(key => rule(`.ezpug-moment-card.art-${key} .ezpug-moment-art`, key)),
  ].join('\n')
}
