/**
 * **The welcome's banners** (PRD-07 T5). A banner is a picture with a key,
 * `hud/banners/<key>.png`, and nothing can put a picture on a HUD at runtime:
 * the plugin sets a class on the welcome (`banner-<key>`) and a stylesheet
 * says which picture that class means. So the stylesheet is written from the
 * folder, like the contract's key list (`keys.ts`), and a test fails when the
 * two disagree. No class, or a class for a key the addon does not hold, is
 * the house banner, `default`: the rule for the picture's own box names it,
 * and only a class this file knows overrides it.
 *
 * Every banner is {@link BANNER_WIDTH} × {@link BANNER_HEIGHT}, which is the
 * welcome's banner box (400 × 225 in the layout) at twice its size, so a 4K
 * screen draws it from its own pixels. `pnpm hud:banner <key> <file>` brings
 * any picture to that size the way the house one was: fitted whole, centred,
 * the rest transparent, with ImageMagick's `convert` from the box (the same
 * tool the platform's art pipeline and the read-back use).
 */
import { spawnSync } from 'node:child_process'
import { join } from 'node:path'

export const BANNER_WIDTH = 800
export const BANNER_HEIGHT = 450

/** Where the generated stylesheet lives, relative to `hud/`. */
export const BANNER_STYLES = 'styles/ezpug_banners.css'

/** A banner's picture as the stylesheet names it: the compiled texture in the addon. */
export const bannerTexture = (key: string) =>
  `s2r://panorama/images/custom_game/ezpug/banners/${key}.vtex`

/** The stylesheet the welcome includes for its banner, as source. */
export function renderBannerStyles(keys: string[], fallback: string): string {
  const rule = (selector: string, key: string) =>
    `${selector}\n{\n\tbackground-image: url( "${bannerTexture(key)}" );\n}\n`
  return [
    `/*
  Generated by \`pnpm hud:banner\` and \`pnpm hud:keys\` from the pictures in hud/banners/.
  Never edited by hand: hud/test/banners.test.ts fails when this file and that folder
  disagree. The house banner unless the welcome carries a class for a key this addon holds.
*/
`,
    rule('.ezpug-welcome-banner', fallback),
    ...keys
      .filter(key => key !== fallback)
      .map(key => rule(`.ezpug-welcome.banner-${key} .ezpug-welcome-banner`, key)),
  ].join('\n')
}

/**
 * `file`, fitted whole into the banner's size and centred on a transparent
 * canvas, written as an 8-bit RGBA PNG at `out` with no metadata (so the same
 * picture is the same bytes).
 */
export function fitBanner(file: string, out: string): void {
  const size = `${BANNER_WIDTH}x${BANNER_HEIGHT}`
  const result = spawnSync(
    'convert',
    [
      file,
      '-resize',
      size,
      '-background',
      'none',
      '-gravity',
      'center',
      '-extent',
      size,
      '-strip',
      `png32:${out}`,
    ],
    { encoding: 'utf8' },
  )
  if (result.error)
    throw new Error(`ImageMagick's convert is needed for a banner: ${result.error.message}`)
  if (result.status !== 0) throw new Error(`convert ${file}: ${result.stderr.trim()}`)
}

/** Where a banner's picture goes in `hud/`. */
export const bannerPath = (hudDir: string, key: string) => join(hudDir, 'banners', `${key}.png`)
