/**
 * **The keys the addon ships, as the contract lists them** (PRD-07 T4). A
 * picture in a custom HUD is compiled into the addon; nothing can put one on
 * screen at runtime. So what a client may ask for is exactly the set of files
 * in two folders here:
 *
 * | in `hud/`             | a key for                                         |
 * | --------------------- | ------------------------------------------------- |
 * | `banners/<key>.png`   | the welcome's banner (`branding.banner`)          |
 * | `art/<key>.png`       | a moment's picture (`moment.art`)                 |
 *
 * `@ezpug/match-api` exports both lists so the platform can offer them in a
 * picker, and it cannot import this private package, so the lists are written
 * into it as a file: `pnpm hud:keys` writes
 * `packages/match-api/src/resources/hud-keys.ts` from the two folders, and a
 * test fails when the file and the folders disagree. A key is kebab-case
 * because it travels in the contract's grammar. Each list has one key every
 * unknown key falls back to, and that file must exist.
 */
import { existsSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

/** Where the generated module lives, relative to the repo. */
export const KEYS_MODULE = 'packages/match-api/src/resources/hud-keys.ts'

/** The banner an unknown or absent banner key shows: the house one. */
export const DEFAULT_BANNER = 'default'

/** The picture an unknown or absent art key shows: the platform's empty card sleeve. */
export const DEFAULT_ART = 'empty'

const KEY = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/

export interface HudKeys {
  banners: string[]
  art: string[]
}

function keysIn(hudDir: string, folder: string): string[] {
  const dir = join(hudDir, folder)
  if (!existsSync(dir)) return []
  const keys: string[] = []
  for (const file of readdirSync(dir).sort()) {
    if (!file.endsWith('.png')) throw new Error(`hud/${folder}/${file}: a picture here is a .png`)
    const key = file.slice(0, -'.png'.length)
    if (!KEY.test(key)) throw new Error(`hud/${folder}/${file}: a key is kebab-case`)
    keys.push(key)
  }
  return keys
}

/** Every key `hud/` holds a picture for, sorted. Refuses a folder without its fallback. */
export function hudKeys(hudDir: string): HudKeys {
  const keys = { banners: keysIn(hudDir, 'banners'), art: keysIn(hudDir, 'art') }
  if (!keys.banners.includes(DEFAULT_BANNER))
    throw new Error(
      `hud/banners/${DEFAULT_BANNER}.png is missing: every other key falls back to it`,
    )
  if (!keys.art.includes(DEFAULT_ART))
    throw new Error(`hud/art/${DEFAULT_ART}.png is missing: every other key falls back to it`)
  return keys
}

/** One list, laid out the way Biome would: on one line when it fits in 100 columns. */
function list(name: string, keys: string[]): string {
  const line = `export const ${name} = [${keys.map(key => `'${key}'`).join(', ')}] as const\n`
  if (line.length <= 101) return line
  return `export const ${name} = [\n${keys.map(key => `  '${key}',\n`).join('')}] as const\n`
}

/** The module `@ezpug/match-api` exports the lists from, as source. */
export function renderKeysModule(keys: HudKeys): string {
  return `// Generated by \`pnpm hud:keys\` from the pictures in hud/banners/ and hud/art/.
// Never edited by hand: a key is a file in the addon, and hud/test/keys.test.ts
// fails when this list and those folders disagree.

/** Every banner the addon ships, by key (\`hud/banners/<key>.png\`). */
${list('HUD_BANNER_KEYS', keys.banners)}
/** Every moment picture the addon ships, by key (\`hud/art/<key>.png\`). */
${list('HUD_ART_KEYS', keys.art)}`
}
